---
language: node_js
node_js:
  - "5.1"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^3.6"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember test
  
after_script:
  - CODECLIMATE_REPO_TOKEN=bf2c4ddc222de5547c76063a2b1ea369461c96af580ed2d9fb710496b1418bef codeclimate-test-reporter < lcov.dat

